services:
  - type: web
    name: pomodoro-tasks-api
    env: node
    buildCommand: npm run build:render
    startCommand: node dist/server.js
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_PATH
        value: /tmp/database.sqlite